/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.farmsys.UI;

import com.farmsys.Entity.KhoHang;
import com.farmsys.Helper.DateHelper;
import com.farmsys.Helper.MsgBox;
import com.farmsys.dao.KhoHangDAO;
import com.farmsys.dao.NhatKyDAO;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenTrung
 */
public class KhoHangJPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhoHangJPanel
     */
    public KhoHangJPanel() {
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HoaDonJDialog = new javax.swing.JDialog();
        pnlhoadon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNgayGD = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblNguoiBan = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblQR = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblGiaban = new javax.swing.JLabel();
        lblSanPham = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnkhongin = new javax.swing.JButton();
        btnInHD = new javax.swing.JButton();
        PnlTong = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        pnltimkiem = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblKhoHang = new javax.swing.JTable();
        pnledit = new javax.swing.JPanel();
        txtTenGian = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenCay = new javax.swing.JTextField();
        txtTrongLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSLBan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaTH = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNgayTH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();

        HoaDonJDialog.setTitle("Hóa Đơn FarmSys");
        HoaDonJDialog.setAlwaysOnTop(true);
        HoaDonJDialog.setBackground(new java.awt.Color(255, 255, 255));
        HoaDonJDialog.setMinimumSize(new java.awt.Dimension(507, 700));
        HoaDonJDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlhoadon.setBackground(new java.awt.Color(255, 255, 255));
        pnlhoadon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlhoadon.setMinimumSize(new java.awt.Dimension(470, 630));
        pnlhoadon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("PHIẾU THANH THANH TOÁN");
        pnlhoadon.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 99, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("www.farmsys.com");
        pnlhoadon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 41, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("35-37 Phạm Hữu Lầu, Khu phố 2, Phường Phú Mỹ, Quận 7, Thành phố Hồ Chí Minh, Việt Nam");
        pnlhoadon.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 64, 440, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        pnlhoadon.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 83, 446, 10));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("NÔNG TRẠI THỦY CANH 4.0");
        pnlhoadon.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 13, -1, -1));

        jLabel15.setText("Ngày giao dịch:");
        pnlhoadon.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 139, -1, -1));

        lblNgayGD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNgayGD.setText("20/07/2021 20:20");
        pnlhoadon.add(lblNgayGD, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 139, 190, -1));

        jLabel16.setText("Người bán:");
        pnlhoadon.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 164, 74, -1));

        lblNguoiBan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNguoiBan.setText("Vương Nguyên Trung");
        pnlhoadon.add(lblNguoiBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 164, 140, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        pnlhoadon.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, 446, 10));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Tổng tiền:");
        pnlhoadon.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 60, 20));

        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTongTien.setText("0 ");
        pnlhoadon.add(lblTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 90, 20));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        pnlhoadon.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 324, 446, 10));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("(Giá trên đã bao gồm thuế GTGT)");
        pnlhoadon.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 340, 275, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        pnlhoadon.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 365, 446, 10));
        pnlhoadon.add(lblQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 200));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/FarmSys.png"))); // NOI18N
        pnlhoadon.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 230, 200));

        jLabel21.setText("Tên sản phẩm:");
        pnlhoadon.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 189, -1, -1));

        jLabel22.setText("Giá bán:");
        pnlhoadon.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 239, -1, -1));

        jLabel23.setText("Số lượng:");
        pnlhoadon.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 214, -1, -1));

        lblGiaban.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGiaban.setText("jLabel13");
        pnlhoadon.add(lblGiaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 239, 120, -1));

        lblSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSanPham.setText("jLabel13");
        pnlhoadon.add(lblSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 189, 130, -1));

        lblSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSoLuong.setText("jLabel13");
        pnlhoadon.add(lblSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 214, 80, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("$");
        pnlhoadon.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 20, 20));

        HoaDonJDialog.getContentPane().add(pnlhoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 590));

        btnkhongin.setText("Không in hóa đơn");
        btnkhongin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhonginActionPerformed(evt);
            }
        });
        HoaDonJDialog.getContentPane().add(btnkhongin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, -1, -1));

        btnInHD.setText("In hóa đơn");
        btnInHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHDActionPerformed(evt);
            }
        });
        HoaDonJDialog.getContentPane().add(btnInHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, -1, -1));

        setBackground(new java.awt.Color(255, 255, 255));

        PnlTong.setBackground(new java.awt.Color(255, 255, 255));
        PnlTong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(102, 255, 102));
        lbltitle.setText("Quản Lý Kho Hàng");
        PnlTong.add(lbltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 186, -1));

        pnltimkiem.setBackground(new java.awt.Color(255, 255, 255));
        pnltimkiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        pnltimkiem.setForeground(new java.awt.Color(51, 51, 51));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Tên Cây");

        javax.swing.GroupLayout pnltimkiemLayout = new javax.swing.GroupLayout(pnltimkiem);
        pnltimkiem.setLayout(pnltimkiemLayout);
        pnltimkiemLayout.setHorizontalGroup(
            pnltimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltimkiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnltimkiemLayout.setVerticalGroup(
            pnltimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltimkiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnltimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PnlTong.add(pnltimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 548, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/icons8_synchronize_25px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        PnlTong.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 30, -1));

        tblKhoHang.setAutoCreateRowSorter(true);
        tblKhoHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblKhoHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên Giàn", "Tên Cây", "Trọng Lượng", "Ngày TH", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhoHang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKhoHang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKhoHang.setShowGrid(false);
        tblKhoHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhoHangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblKhoHang);

        PnlTong.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 548, 420));

        pnledit.setBackground(new java.awt.Color(204, 255, 204));
        pnledit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTenGian.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tên giàn:");

        txtTenCay.setEditable(false);

        txtTrongLuong.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tên cây:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("SL Kho:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Ngày TH:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Giá Bán");

        btnBuy.setBackground(new java.awt.Color(255, 255, 255));
        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/Dollar.png"))); // NOI18N
        btnBuy.setText("BUY");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SL Bán");

        txtGiaBan.setForeground(new java.awt.Color(102, 102, 102));
        txtGiaBan.setText("0$");
        txtGiaBan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGiaBanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGiaBanFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Mã TH:");

        txtMaTH.setEditable(false);

        txtNgayTH.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Tổng tiền:");

        txtThanhTien.setEditable(false);

        javax.swing.GroupLayout pnleditLayout = new javax.swing.GroupLayout(pnledit);
        pnledit.setLayout(pnleditLayout);
        pnleditLayout.setHorizontalGroup(
            pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnleditLayout.createSequentialGroup()
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnleditLayout.createSequentialGroup()
                        .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnleditLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnleditLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayTH, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaTH, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenGian, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenCay, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnleditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnleditLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnleditLayout.createSequentialGroup()
                                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                    .addComponent(txtSLBan))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnleditLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtMaTH, txtTenCay, txtTenGian});

        pnleditLayout.setVerticalGroup(
            pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnleditLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaTH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenGian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenCay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTrongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayTH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(pnleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSLBan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pnleditLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtMaTH, txtTenCay, txtTenGian});

        pnleditLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtGiaBan, txtSLBan});

        PnlTong.add(pnledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 460, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, 1149, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhoHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoHangMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.index = tblKhoHang.getSelectedRow();
            this.edit();

        }
    }//GEN-LAST:event_tblKhoHangMouseClicked

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        this.Buy();
        this.createQRcode();
        lblQR.setIcon(new ImageIcon("src\\QRcode\\QRHoaDon.png"));
    }//GEN-LAST:event_btnBuyActionPerformed

    private void txtGiaBanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiaBanFocusGained
        if (txtGiaBan.getText().equalsIgnoreCase("0$")) {
            txtGiaBan.setText("");
            txtGiaBan.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtGiaBanFocusGained

    private void txtGiaBanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiaBanFocusLost
        if (txtGiaBan.getText().length() == 0) {
            txtGiaBan.setText("0$");
            txtGiaBan.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtGiaBanFocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.fillTable();
        txtTimKiem.setText("");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnkhonginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhonginActionPerformed
        HoaDonJDialog.setVisible(false);
        clear();
    }//GEN-LAST:event_btnkhonginActionPerformed

    private void btnInHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHDActionPerformed
        printPanel(pnlhoadon);
        HoaDonJDialog.setVisible(false);
        clear();
    }//GEN-LAST:event_btnInHDActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        this.timKiem();    }//GEN-LAST:event_txtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog HoaDonJDialog;
    private javax.swing.JPanel PnlTong;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnInHD;
    private javax.swing.JButton btnkhongin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblGiaban;
    private javax.swing.JLabel lblNgayGD;
    private javax.swing.JLabel lblNguoiBan;
    private javax.swing.JLabel lblQR;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel pnledit;
    private javax.swing.JPanel pnlhoadon;
    private javax.swing.JPanel pnltimkiem;
    private javax.swing.JTable tblKhoHang;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaTH;
    private javax.swing.JTextField txtNgayTH;
    private javax.swing.JTextField txtSLBan;
    private javax.swing.JTextField txtTenCay;
    private javax.swing.JTextField txtTenGian;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTrongLuong;
    // End of variables declaration//GEN-END:variables
    KhoHangDAO khdao = new KhoHangDAO();
    NhatKyDAO nkdao = new NhatKyDAO();
    int index = 0;

    void init() {
        txtTimKiem.grabFocus();
        fillTable();
        HoaDonJDialog.setLocationRelativeTo(this);

    }

    void Buy() {
        if (Validation()) {
            int kh = Integer.parseInt(txtMaTH.getText());
            Float TrongLuong = Float.parseFloat(txtTrongLuong.getText());
            Double Coin = Double.parseDouble(txtThanhTien.getText());
            Float gb = Float.parseFloat(txtGiaBan.getText());
            Float slb = Float.parseFloat(txtSLBan.getText());
//            Double tongtien = Double.parseDouble(lblTongTien.getText());
            Double Coin2 = Coin + (gb * slb);
//            Double hoadontongtien = tongtien + (gb * slb);
            Float TrongLuong2 = TrongLuong - slb;

            try {
                khdao.update(TrongLuong2, Coin2, kh);
                if (slb > TrongLuong) {
                    MsgBox.alert(this, "Giao Dịch Thất Bại !");
                } else {
                    this.fillTable();
                    MsgBox.alert(this, "Giao Dịch Thành Công !");
                    this.UpdateStt();
                    HoaDonJDialog.setVisible(true);
                    lblNgayGD.setText(DateHelper.now() + "");
                    lblSanPham.setText(txtTenCay.getText());
                    lblGiaban.setText(txtGiaBan.getText() + " /kg");
                    lblSoLuong.setText(txtSLBan.getText() + " kg");
                    lblTongTien.setText((slb * gb) + "");

                }

            } catch (Exception e) {
                MsgBox.alert(this, "Giao Dịch Thất Bại !");
            }

        }

    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblKhoHang.getModel();
        model.setRowCount(0);
        try {
            String keywords = txtTimKiem.getText();
            List<KhoHang> list = khdao.selectByKeyword(keywords);
            for (KhoHang kh : list) {
                Object[] row = {
                    kh.getTenGian(), kh.getTenCay(), kh.getTrongLuong(),
                    kh.getNgayTH(), kh.getGiaThanh()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void edit() {
        try {
            String TenDan = (String) tblKhoHang.getValueAt(this.index, 0);
            KhoHang kh = khdao.selectById(TenDan);
            this.setForm(kh);

            this.updateStatus();
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void clear() {
        txtMaTH.setText("");
        txtNgayTH.setText("");
        txtTrongLuong.setText("");
        txtTenCay.setText("");
        txtTenGian.setText("");
        txtThanhTien.setText("");
        txtGiaBan.setText("");
        txtSLBan.setText("");

        this.index = 0;
        this.updateStatus();

    }

    void setForm(KhoHang kh) {
        txtMaTH.setText(String.valueOf(kh.getMaTH()));
        txtTenGian.setText(kh.getTenGian());
        txtTenCay.setText(kh.getTenCay());
        txtTrongLuong.setText(String.valueOf(kh.getTrongLuong()));
        txtNgayTH.setText(kh.getNgayTH().toString());
        txtThanhTien.setText(kh.getGiaThanh() + "");

    }

    void updateStatus() {
        boolean edit = (this.index >= 0);
        boolean first = (this.index == 0);
        boolean last = (this.index == tblKhoHang.getRowCount() - 1);
        btnBuy.setEnabled(edit);

    }

    boolean Validation() {
        if (txtMaTH.getText().isEmpty()) {
            MsgBox.alert(this, "Chưa chọn sản phẩm !");
            return false;
        }
        if (txtSLBan.getText().isEmpty()) {
            MsgBox.alert(this, "Trọng lượng không được để trống!");
            txtSLBan.setFocusable(true);
            return false;
        }

        if (txtSLBan.getText().isEmpty()) {
            MsgBox.alert(this, "Giá bán không được để trống!");
            txtSLBan.setFocusable(true);
            return false;
        }
        try {
            Float.parseFloat(txtSLBan.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "Số lượng bán không được nhập chữ !");
            txtSLBan.requestFocus();
            return false;
        }

        try {
            Float.parseFloat(txtGiaBan.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "Giá bán không được nhập chữ !");
            txtGiaBan.requestFocus();
            return false;
        }

        if ((Float.parseFloat(txtGiaBan.getText()) < 0)) {
            MsgBox.alert(this, "Bạn phải nhập số dương cho giá bán!");
            txtGiaBan.requestFocus();
            return false;

        }
        if ((Float.parseFloat(txtSLBan.getText()) < 0)) {
            MsgBox.alert(this, "Bạn phải nhập số dương cho số lượng bán!");
            txtSLBan.requestFocus();
            return false;
        }
        if (txtGiaBan.getText().length() > 7) {
            MsgBox.alert(this, "Giá cao hơn so với thị trường !");
            txtGiaBan.requestFocus();
            return false;
        }
        return true;
    }

    void UpdateStt() {
        try {
            nkdao.updateTrangThaiTH(txtTenGian.getText());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void timKiem() {
        this.fillTable();
        this.clear();
        this.index = 0;
    }

    private void printPanel(JPanel panel) {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("In hóa đơn");
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D = (Graphics2D) graphics;
                graphics2D.translate(pageFormat.getImageableX() * 10, pageFormat.getImageableY() * 10);
                graphics2D.scale(0.5, 0.5);
                panel.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean returnResult = printerJob.printDialog();
        if (returnResult) {
            try {
                printerJob.print();
            } catch (Exception e) {
            }
        }
    }

    private void createQRcode() {
        String thongtin = txtTenCay.getText() + ", "
                + " | " + txtTenGian.getText() + ", "
                + " | " + txtNgayTH.getText() + ", "
                + " | " + lblNgayGD.getText() + ", "
                + " | " + lblSoLuong.getText() + ", "
                + " | " + lblGiaban.getText() + ", "
                + " | " + lblTongTien.getText() + ", ";
        try {
            String qrCodeData = thongtin;
            String filePath = "src\\QRcode\\QRHoaDon.png";
            String charset = "UTF-8"; // or "ISO-8859-1"
            Map< EncodeHintType, ErrorCorrectionLevel> hintMap = new EnumMap<>(EncodeHintType.class);
            hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
            BitMatrix matrix = new MultiFormatWriter().encode(
                    new String(qrCodeData.getBytes(charset), charset),
                    BarcodeFormat.QR_CODE, 200, 200, hintMap);
            MatrixToImageWriter.writeToFile(matrix, filePath.substring(filePath
                    .lastIndexOf('.') + 1), new File(filePath));
            System.out.println("QR Code image created successfully!");
        } catch (WriterException | IOException e) {
            System.err.println(e);
        }
    }
}
