
package com.farmsys.UI;

import com.farmsys.Entity.NhanVien;
import com.farmsys.Entity.NhatKy;
import com.farmsys.data.JsonResult;
import com.farmsys.Helper.Auth;
import com.farmsys.Helper.HandleAPI;
import com.farmsys.Helper.MsgBox;
import com.farmsys.Helper.XImage;
import com.farmsys.dao.KhoHangDAO;
import com.farmsys.dao.NhanVienDAO;
import com.farmsys.dao.NhatKyDAO;
import com.farmsys.dao.ThuHoachDAO;
import jaco.mp3.player.MP3Player;
import java.awt.event.ActionEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.core.MatOfRect;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.highgui.Highgui;
import org.opencv.highgui.VideoCapture;
import org.opencv.objdetect.CascadeClassifier;

/**
 *
 * @author trieu
 */
public class TongQuan extends javax.swing.JFrame {

    /**
     * Creates new form TongQuan
     */
    public TongQuan() {
        initComponents();
        init();
        System.out.println(TongQuan.class.getResource("haarcascade_frontalface_alt.xml").getPath().substring(1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penalTong = new javax.swing.JPanel();
        pnlfoot = new javax.swing.JPanel();
        pnlhead = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        pnltongquat = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        lblsunrain = new javax.swing.JLabel();
        pnlkhohang = new javax.swing.JPanel();
        lblDemKhoHang = new javax.swing.JLabel();
        LogoKhohang = new javax.swing.JLabel();
        pnldoing = new javax.swing.JPanel();
        lblDemDangLam = new javax.swing.JLabel();
        LogoDoing = new javax.swing.JLabel();
        pnltodo = new javax.swing.JPanel();
        lblDemNhanViec = new javax.swing.JLabel();
        logoNhanviec = new javax.swing.JLabel();
        btnThongke = new javax.swing.JButton();
        lblcongvieccanlam = new javax.swing.JLabel();
        lblkhohang = new javax.swing.JLabel();
        lblnhanviec = new javax.swing.JLabel();
        lblbonus = new javax.swing.JLabel();
        pnlBonus = new javax.swing.JPanel();
        lblDemDoneByMonth = new javax.swing.JLabel();
        logoDollar = new javax.swing.JLabel();
        lblcaycanTH = new javax.swing.JLabel();
        pnlCaycanTH = new javax.swing.JPanel();
        lblDemSoCayTH = new javax.swing.JLabel();
        logocaycanTH = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhatKy = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblweather = new javax.swing.JLabel();
        pnlhienthiNV = new javax.swing.JPanel();
        lbldemNV = new javax.swing.JLabel();
        logocaycanTH1 = new javax.swing.JLabel();
        lblNhanvien = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Manhinhlive = new javax.swing.JPanel();
        pnlavatar = new javax.swing.JPanel();
        lblhoten = new javax.swing.JLabel();
        lblvaitro = new javax.swing.JLabel();
        imageAvatar = new com.farmsys.Helper.ImageAvatar();
        lblLogout = new javax.swing.JLabel();
        pnlmenu = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        logodashboard = new javax.swing.JLabel();
        lbldashboard = new javax.swing.JLabel();
        pnlCamera = new javax.swing.JPanel();
        logolive = new javax.swing.JLabel();
        lblcamera = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlTrangchu = new javax.swing.JPanel();
        logotrangchu = new javax.swing.JLabel();
        lbltrangchu = new javax.swing.JLabel();
        TabsMnu = new javax.swing.JTabbedPane();
        pnltruongphong = new javax.swing.JPanel();
        pnlThoiTiet = new javax.swing.JPanel();
        logoThoitiet = new javax.swing.JLabel();
        lblthoitiet = new javax.swing.JLabel();
        pnlGiaoViec = new javax.swing.JPanel();
        logoGiaoviec = new javax.swing.JLabel();
        lblGiaoviec = new javax.swing.JLabel();
        pnlGianTrong = new javax.swing.JPanel();
        logogiantrong = new javax.swing.JLabel();
        lblgiantrong = new javax.swing.JLabel();
        pnlCayTrong = new javax.swing.JPanel();
        logocaytrong2 = new javax.swing.JLabel();
        lblcaytrong2 = new javax.swing.JLabel();
        pnlNhatKy = new javax.swing.JPanel();
        logoNhatKy = new javax.swing.JLabel();
        lblcaytrong3 = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        logoNhanVien = new javax.swing.JLabel();
        lblcaytrong1 = new javax.swing.JLabel();
        pnlnhanvien = new javax.swing.JPanel();
        pnlThoiTiet1 = new javax.swing.JPanel();
        logoThoitiet1 = new javax.swing.JLabel();
        lblthoitiet1 = new javax.swing.JLabel();
        pnlxacnhan = new javax.swing.JPanel();
        logoxnht = new javax.swing.JLabel();
        lblxnht = new javax.swing.JLabel();
        pnlnhanviec = new javax.swing.JPanel();
        logomenunhanviec = new javax.swing.JLabel();
        lblmenunhanviec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FarmSys");
        setBackground(new java.awt.Color(255, 255, 255));

        penalTong.setBackground(new java.awt.Color(204, 255, 204));
        penalTong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlfoot.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout pnlfootLayout = new javax.swing.GroupLayout(pnlfoot);
        pnlfoot.setLayout(pnlfootLayout);
        pnlfootLayout.setHorizontalGroup(
            pnlfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
        );
        pnlfootLayout.setVerticalGroup(
            pnlfootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        penalTong.add(pnlfoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1340, 10));

        pnlhead.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout pnlheadLayout = new javax.swing.GroupLayout(pnlhead);
        pnlhead.setLayout(pnlheadLayout);
        pnlheadLayout.setHorizontalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1590, Short.MAX_VALUE)
        );
        pnlheadLayout.setVerticalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        penalTong.add(pnlhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -10, 1590, 20));

        pnltongquat.setBackground(new java.awt.Color(255, 255, 255));
        pnltongquat.setMinimumSize(new java.awt.Dimension(1090, 750));
        pnltongquat.setPreferredSize(new java.awt.Dimension(1090, 750));
        pnltongquat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDongHo.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(51, 51, 51));
        lblDongHo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnltongquat.add(lblDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 190, 60));

        lblsunrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/sun_100px.png"))); // NOI18N
        lblsunrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsunrainMouseClicked(evt);
            }
        });
        pnltongquat.add(lblsunrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 100, 100));

        pnlkhohang.setBackground(new java.awt.Color(255, 204, 153));
        pnlkhohang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlkhohang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlkhohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlkhohangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlkhohangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlkhohangMouseExited(evt);
            }
        });

        lblDemKhoHang.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblDemKhoHang.setText("0");

        LogoKhohang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/box_50px.png"))); // NOI18N

        javax.swing.GroupLayout pnlkhohangLayout = new javax.swing.GroupLayout(pnlkhohang);
        pnlkhohang.setLayout(pnlkhohangLayout);
        pnlkhohangLayout.setHorizontalGroup(
            pnlkhohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlkhohangLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblDemKhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoKhohang, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlkhohangLayout.setVerticalGroup(
            pnlkhohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDemKhoHang, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(LogoKhohang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltongquat.add(pnlkhohang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 220, 120));

        pnldoing.setBackground(new java.awt.Color(255, 255, 204));
        pnldoing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnldoing.setToolTipText("");
        pnldoing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnldoing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnldoingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnldoingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnldoingMouseExited(evt);
            }
        });

        lblDemDangLam.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblDemDangLam.setText("0");

        LogoDoing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/stretching_50px.png"))); // NOI18N

        javax.swing.GroupLayout pnldoingLayout = new javax.swing.GroupLayout(pnldoing);
        pnldoing.setLayout(pnldoingLayout);
        pnldoingLayout.setHorizontalGroup(
            pnldoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldoingLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblDemDangLam, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogoDoing, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnldoingLayout.setVerticalGroup(
            pnldoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDemDangLam, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(LogoDoing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltongquat.add(pnldoing, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 220, 120));

        pnltodo.setBackground(new java.awt.Color(255, 204, 204));
        pnltodo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnltodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnltodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnltodoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnltodoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnltodoMouseExited(evt);
            }
        });

        lblDemNhanViec.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblDemNhanViec.setText("0");

        logoNhanviec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/Document_50px.png"))); // NOI18N

        javax.swing.GroupLayout pnltodoLayout = new javax.swing.GroupLayout(pnltodo);
        pnltodo.setLayout(pnltodoLayout);
        pnltodoLayout.setHorizontalGroup(
            pnltodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltodoLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblDemNhanViec, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(logoNhanviec, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnltodoLayout.setVerticalGroup(
            pnltodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDemNhanViec, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(logoNhanviec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltongquat.add(pnltodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 120));

        btnThongke.setBackground(new java.awt.Color(255, 255, 255));
        btnThongke.setText("Bảng thống kê doanh thu");
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });
        pnltongquat.add(btnThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 190, 30));

        lblcongvieccanlam.setText("Công việc đang làm:");
        pnltongquat.add(lblcongvieccanlam, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        lblkhohang.setText("Kho hàng:");
        pnltongquat.add(lblkhohang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        lblnhanviec.setText("Nhận việc:");
        pnltongquat.add(lblnhanviec, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblbonus.setText("Bonus:");
        pnltongquat.add(lblbonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        pnlBonus.setBackground(new java.awt.Color(153, 153, 255));
        pnlBonus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBonus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBonus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBonusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBonusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBonusMouseExited(evt);
            }
        });

        lblDemDoneByMonth.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblDemDoneByMonth.setText("0");

        logoDollar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/icons8_heavy_dollar_sign_50px.png"))); // NOI18N

        javax.swing.GroupLayout pnlBonusLayout = new javax.swing.GroupLayout(pnlBonus);
        pnlBonus.setLayout(pnlBonusLayout);
        pnlBonusLayout.setHorizontalGroup(
            pnlBonusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBonusLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblDemDoneByMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoDollar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBonusLayout.setVerticalGroup(
            pnlBonusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDemDoneByMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(logoDollar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltongquat.add(pnlBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 220, 120));

        lblcaycanTH.setText("Số cây cần thu hoạch:");
        pnltongquat.add(lblcaycanTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        pnlCaycanTH.setBackground(new java.awt.Color(153, 255, 153));
        pnlCaycanTH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDemSoCayTH.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblDemSoCayTH.setText("0");

        logocaycanTH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/tractor_50px.png"))); // NOI18N

        javax.swing.GroupLayout pnlCaycanTHLayout = new javax.swing.GroupLayout(pnlCaycanTH);
        pnlCaycanTH.setLayout(pnlCaycanTHLayout);
        pnlCaycanTHLayout.setHorizontalGroup(
            pnlCaycanTHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCaycanTHLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblDemSoCayTH, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logocaycanTH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCaycanTHLayout.setVerticalGroup(
            pnlCaycanTHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDemSoCayTH, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(logocaycanTH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltongquat.add(pnlCaycanTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 220, 120));
        pnltongquat.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 700, 10));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblNhatKy.setAutoCreateRowSorter(true);
        tblNhatKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên công việc", "Tên Cây", "Tên Giàn", "Chi tiết công việc", "Người tạo", "Nhân viên", "Bắt đầu", "Kết thúc", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhatKy.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblNhatKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblNhatKy.setDropMode(javax.swing.DropMode.INSERT);
        tblNhatKy.setFillsViewportHeight(true);
        tblNhatKy.setFocusable(false);
        tblNhatKy.setGridColor(new java.awt.Color(255, 255, 255));
        tblNhatKy.setMinimumSize(new java.awt.Dimension(750, 480));
        tblNhatKy.setRowHeight(40);
        tblNhatKy.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNhatKy.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNhatKy.setUpdateSelectionOnSort(false);
        tblNhatKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhatKyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhatKy);
        if (tblNhatKy.getColumnModel().getColumnCount() > 0) {
            tblNhatKy.getColumnModel().getColumn(0).setResizable(false);
            tblNhatKy.getColumnModel().getColumn(1).setResizable(false);
            tblNhatKy.getColumnModel().getColumn(2).setResizable(false);
            tblNhatKy.getColumnModel().getColumn(3).setResizable(false);
            tblNhatKy.getColumnModel().getColumn(4).setResizable(false);
            tblNhatKy.getColumnModel().getColumn(5).setResizable(false);
            tblNhatKy.getColumnModel().getColumn(6).setResizable(false);
            tblNhatKy.getColumnModel().getColumn(7).setResizable(false);
            tblNhatKy.getColumnModel().getColumn(8).setResizable(false);
        }
        tblNhatKy.getAccessibleContext().setAccessibleParent(pnltongquat);

        pnltongquat.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 1020, 270));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/refresh_25px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnltongquat.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 30));

        lblweather.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 11)); // NOI18N
        lblweather.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblweather.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/weather_16px.png"))); // NOI18N
        lblweather.setText(":");
        lblweather.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblweatherMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblweatherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblweatherMouseExited(evt);
            }
        });
        pnltongquat.add(lblweather, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 250, 30));

        pnlhienthiNV.setBackground(new java.awt.Color(102, 255, 204));
        pnlhienthiNV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlhienthiNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlhienthiNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlhienthiNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlhienthiNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlhienthiNVMouseExited(evt);
            }
        });

        lbldemNV.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbldemNV.setText("0");

        logocaycanTH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/user_50px.png"))); // NOI18N

        javax.swing.GroupLayout pnlhienthiNVLayout = new javax.swing.GroupLayout(pnlhienthiNV);
        pnlhienthiNV.setLayout(pnlhienthiNVLayout);
        pnlhienthiNVLayout.setHorizontalGroup(
            pnlhienthiNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhienthiNVLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lbldemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logocaycanTH1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlhienthiNVLayout.setVerticalGroup(
            pnlhienthiNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbldemNV, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(logocaycanTH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltongquat.add(pnlhienthiNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 220, 120));

        lblNhanvien.setText("Nhân viên:");
        pnltongquat.add(lblNhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        jLabel1.setText("Nhật ký của tháng hiện tại:");
        pnltongquat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        tabs.addTab("tab1", pnltongquat);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1090, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Manhinhlive.setMinimumSize(new java.awt.Dimension(1090, 750));
        Manhinhlive.setPreferredSize(new java.awt.Dimension(1090, 750));
        Manhinhlive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManhinhliveMouseClicked(evt);
            }
        });
        Manhinhlive.setLayout(new javax.swing.BoxLayout(Manhinhlive, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(Manhinhlive, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 108, 1020, 563));

        tabs.addTab("tab3", jPanel1);

        penalTong.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -22, 1080, 790));

        pnlavatar.setBackground(new java.awt.Color(255, 255, 255));

        lblhoten.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblhoten.setForeground(new java.awt.Color(51, 51, 51));
        lblhoten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhoten.setText("Vương Nguyên Trung");
        lblhoten.setAutoscrolls(true);

        lblvaitro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblvaitro.setForeground(new java.awt.Color(51, 51, 51));
        lblvaitro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvaitro.setText("Trưởng phòng");

        lblLogout.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(51, 153, 255));
        lblLogout.setText("Log out");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlavatarLayout = new javax.swing.GroupLayout(pnlavatar);
        pnlavatar.setLayout(pnlavatarLayout);
        pnlavatarLayout.setHorizontalGroup(
            pnlavatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlavatarLayout.createSequentialGroup()
                .addGroup(pnlavatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlavatarLayout.createSequentialGroup()
                        .addComponent(lblvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblhoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlavatarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout)
                .addGap(19, 19, 19))
            .addGroup(pnlavatarLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlavatarLayout.setVerticalGroup(
            pnlavatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlavatarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblhoten, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblLogout))
        );

        penalTong.add(pnlavatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 180));

        pnlmenu.setBackground(new java.awt.Color(255, 255, 255));

        pnlDashboard.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseExited(evt);
            }
        });

        logodashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/Bar chart.png"))); // NOI18N

        lbldashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logodashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logodashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(lbldashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlCamera.setBackground(new java.awt.Color(255, 255, 255));
        pnlCamera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCamera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCameraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCameraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCameraMouseExited(evt);
            }
        });

        logolive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/youtube_live_25px.png"))); // NOI18N

        lblcamera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcamera.setText("Camera quan sát");

        javax.swing.GroupLayout pnlCameraLayout = new javax.swing.GroupLayout(pnlCamera);
        pnlCamera.setLayout(pnlCameraLayout);
        pnlCameraLayout.setHorizontalGroup(
            pnlCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCameraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logolive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcamera, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        pnlCameraLayout.setVerticalGroup(
            pnlCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logolive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(lblcamera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlTrangchu.setBackground(new java.awt.Color(255, 255, 255));
        pnlTrangchu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTrangchuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlTrangchuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTrangchuMouseExited(evt);
            }
        });

        logotrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/Home.png"))); // NOI18N

        lbltrangchu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltrangchu.setText("Trang chủ");

        javax.swing.GroupLayout pnlTrangchuLayout = new javax.swing.GroupLayout(pnlTrangchu);
        pnlTrangchu.setLayout(pnlTrangchuLayout);
        pnlTrangchuLayout.setHorizontalGroup(
            pnlTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangchuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logotrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pnlTrangchuLayout.setVerticalGroup(
            pnlTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logotrangchu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(lbltrangchu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlmenuLayout = new javax.swing.GroupLayout(pnlmenu);
        pnlmenu.setLayout(pnlmenuLayout);
        pnlmenuLayout.setHorizontalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCamera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTrangchu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlmenuLayout.setVerticalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCamera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        penalTong.add(pnlmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 220));

        pnltruongphong.setBackground(new java.awt.Color(255, 255, 255));
        pnltruongphong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThoiTiet.setBackground(new java.awt.Color(255, 255, 255));
        pnlThoiTiet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlThoiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThoiTietMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThoiTietMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThoiTietMouseExited(evt);
            }
        });

        logoThoitiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/weather_25px.png"))); // NOI18N

        lblthoitiet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblthoitiet.setText("Thời tiết");

        javax.swing.GroupLayout pnlThoiTietLayout = new javax.swing.GroupLayout(pnlThoiTiet);
        pnlThoiTiet.setLayout(pnlThoiTietLayout);
        pnlThoiTietLayout.setHorizontalGroup(
            pnlThoiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThoiTietLayout.createSequentialGroup()
                .addComponent(logoThoitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblthoitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pnlThoiTietLayout.setVerticalGroup(
            pnlThoiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoThoitiet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(lblthoitiet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltruongphong.add(pnlThoiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, -1, -1));

        pnlGiaoViec.setBackground(new java.awt.Color(255, 255, 255));
        pnlGiaoViec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGiaoViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGiaoViecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGiaoViecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGiaoViecMouseExited(evt);
            }
        });

        logoGiaoviec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/Handshake.png"))); // NOI18N

        lblGiaoviec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGiaoviec.setText("Giao việc");

        javax.swing.GroupLayout pnlGiaoViecLayout = new javax.swing.GroupLayout(pnlGiaoViec);
        pnlGiaoViec.setLayout(pnlGiaoViecLayout);
        pnlGiaoViecLayout.setHorizontalGroup(
            pnlGiaoViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaoViecLayout.createSequentialGroup()
                .addComponent(logoGiaoviec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGiaoviec, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnlGiaoViecLayout.setVerticalGroup(
            pnlGiaoViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoGiaoviec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(lblGiaoviec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltruongphong.add(pnlGiaoViec, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 231, -1, -1));

        pnlGianTrong.setBackground(new java.awt.Color(255, 255, 255));
        pnlGianTrong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGianTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGianTrongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGianTrongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGianTrongMouseExited(evt);
            }
        });

        logogiantrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/tree_planting_25px.png"))); // NOI18N

        lblgiantrong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblgiantrong.setText("Giàn trồng");

        javax.swing.GroupLayout pnlGianTrongLayout = new javax.swing.GroupLayout(pnlGianTrong);
        pnlGianTrong.setLayout(pnlGianTrongLayout);
        pnlGianTrongLayout.setHorizontalGroup(
            pnlGianTrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGianTrongLayout.createSequentialGroup()
                .addComponent(logogiantrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblgiantrong, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pnlGianTrongLayout.setVerticalGroup(
            pnlGianTrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logogiantrong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(lblgiantrong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltruongphong.add(pnlGianTrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 176, 206, -1));

        pnlCayTrong.setBackground(new java.awt.Color(255, 255, 255));
        pnlCayTrong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCayTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCayTrongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCayTrongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCayTrongMouseExited(evt);
            }
        });

        logocaytrong2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/plant_25px.png"))); // NOI18N

        lblcaytrong2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcaytrong2.setText("Cây trồng");

        javax.swing.GroupLayout pnlCayTrongLayout = new javax.swing.GroupLayout(pnlCayTrong);
        pnlCayTrong.setLayout(pnlCayTrongLayout);
        pnlCayTrongLayout.setHorizontalGroup(
            pnlCayTrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCayTrongLayout.createSequentialGroup()
                .addComponent(logocaytrong2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcaytrong2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        pnlCayTrongLayout.setVerticalGroup(
            pnlCayTrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logocaytrong2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(lblcaytrong2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltruongphong.add(pnlCayTrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, 205, -1));

        pnlNhatKy.setBackground(new java.awt.Color(255, 255, 255));
        pnlNhatKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlNhatKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhatKyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNhatKyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNhatKyMouseExited(evt);
            }
        });

        logoNhatKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/Document_25px.png"))); // NOI18N

        lblcaytrong3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcaytrong3.setText("Nhật ký");

        javax.swing.GroupLayout pnlNhatKyLayout = new javax.swing.GroupLayout(pnlNhatKy);
        pnlNhatKy.setLayout(pnlNhatKyLayout);
        pnlNhatKyLayout.setHorizontalGroup(
            pnlNhatKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhatKyLayout.createSequentialGroup()
                .addComponent(logoNhatKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcaytrong3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        pnlNhatKyLayout.setVerticalGroup(
            pnlNhatKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoNhatKy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(lblcaytrong3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltruongphong.add(pnlNhatKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 205, -1));

        pnlNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnlNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseExited(evt);
            }
        });

        logoNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/user_25px.png"))); // NOI18N

        lblcaytrong1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcaytrong1.setText("Nhân viên");

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addComponent(logoNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcaytrong1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(lblcaytrong1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltruongphong.add(pnlNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 205, -1));

        TabsMnu.addTab("tab1", pnltruongphong);

        pnlnhanvien.setBackground(new java.awt.Color(255, 255, 255));

        pnlThoiTiet1.setBackground(new java.awt.Color(255, 255, 255));
        pnlThoiTiet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThoiTiet1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThoiTiet1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThoiTiet1MouseExited(evt);
            }
        });

        logoThoitiet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/weather_25px.png"))); // NOI18N

        lblthoitiet1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblthoitiet1.setText("Thời tiết");

        javax.swing.GroupLayout pnlThoiTiet1Layout = new javax.swing.GroupLayout(pnlThoiTiet1);
        pnlThoiTiet1.setLayout(pnlThoiTiet1Layout);
        pnlThoiTiet1Layout.setHorizontalGroup(
            pnlThoiTiet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThoiTiet1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoThoitiet1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblthoitiet1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        pnlThoiTiet1Layout.setVerticalGroup(
            pnlThoiTiet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoThoitiet1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
            .addComponent(lblthoitiet1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlxacnhan.setBackground(new java.awt.Color(255, 255, 255));
        pnlxacnhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlxacnhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlxacnhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlxacnhanMouseExited(evt);
            }
        });

        logoxnht.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/ok_hand_25px.png"))); // NOI18N

        lblxnht.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblxnht.setText("Xác nhận hoàn thành");

        javax.swing.GroupLayout pnlxacnhanLayout = new javax.swing.GroupLayout(pnlxacnhan);
        pnlxacnhan.setLayout(pnlxacnhanLayout);
        pnlxacnhanLayout.setHorizontalGroup(
            pnlxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlxacnhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoxnht, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblxnht, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlxacnhanLayout.setVerticalGroup(
            pnlxacnhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoxnht, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
            .addComponent(lblxnht, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlnhanviec.setBackground(new java.awt.Color(255, 255, 255));
        pnlnhanviec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlnhanviecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlnhanviecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlnhanviecMouseExited(evt);
            }
        });

        logomenunhanviec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/Document_25px.png"))); // NOI18N

        lblmenunhanviec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblmenunhanviec.setText("Nhận việc");

        javax.swing.GroupLayout pnlnhanviecLayout = new javax.swing.GroupLayout(pnlnhanviec);
        pnlnhanviec.setLayout(pnlnhanviecLayout);
        pnlnhanviecLayout.setHorizontalGroup(
            pnlnhanviecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnhanviecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logomenunhanviec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmenunhanviec, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        pnlnhanviecLayout.setVerticalGroup(
            pnlnhanviecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logomenunhanviec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
            .addComponent(lblmenunhanviec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlnhanvienLayout = new javax.swing.GroupLayout(pnlnhanvien);
        pnlnhanvien.setLayout(pnlnhanvienLayout);
        pnlnhanvienLayout.setHorizontalGroup(
            pnlnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThoiTiet1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlxacnhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlnhanviec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlnhanvienLayout.setVerticalGroup(
            pnlnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlnhanviec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlxacnhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThoiTiet1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(122, 122, 122))
        );

        TabsMnu.addTab("tab1", pnlnhanvien);

        penalTong.add(TabsMnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 230, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penalTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(penalTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlkhohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkhohangMouseClicked
        this.OpenKhohang();
    }//GEN-LAST:event_pnlkhohangMouseClicked

    private void pnldoingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnldoingMouseClicked
        this.Opendoing();
    }//GEN-LAST:event_pnldoingMouseClicked

    private void pnltodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnltodoMouseClicked
        this.OpenTodo();
    }//GEN-LAST:event_pnltodoMouseClicked

    private void pnltodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnltodoMouseEntered
        pnltodo.setBackground(c);
    }//GEN-LAST:event_pnltodoMouseEntered

    private void pnltodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnltodoMouseExited
        pnltodo.setBackground(new Color(255, 204, 204));
    }//GEN-LAST:event_pnltodoMouseExited

    private void pnldoingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnldoingMouseEntered
        pnldoing.setBackground(c);
    }//GEN-LAST:event_pnldoingMouseEntered

    private void pnldoingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnldoingMouseExited
        pnldoing.setBackground(new Color(255, 255, 204));
    }//GEN-LAST:event_pnldoingMouseExited

    private void pnlkhohangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkhohangMouseEntered
        pnlkhohang.setBackground(c);
    }//GEN-LAST:event_pnlkhohangMouseEntered

    private void pnlkhohangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkhohangMouseExited
        pnlkhohang.setBackground(new Color(255, 204, 153));
    }//GEN-LAST:event_pnlkhohangMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.fillTableNhatKyAll();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pnlDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseClicked
        this.Openchart();
    }//GEN-LAST:event_pnlDashboardMouseClicked

    private void pnlDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseEntered
        pnlDashboard.setBackground(c);
    }//GEN-LAST:event_pnlDashboardMouseEntered

    private void pnlDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseExited
        pnlDashboard.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlDashboardMouseExited

    private void pnlTrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTrangchuMouseClicked
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_pnlTrangchuMouseClicked

    private void pnlTrangchuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTrangchuMouseEntered
        pnlTrangchu.setBackground(c);
    }//GEN-LAST:event_pnlTrangchuMouseEntered

    private void pnlTrangchuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTrangchuMouseExited
        pnlTrangchu.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlTrangchuMouseExited

    private void pnlCameraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCameraMouseClicked
        this.OpenLive();
    }//GEN-LAST:event_pnlCameraMouseClicked

    private void pnlCameraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCameraMouseEntered
        pnlCamera.setBackground(c);
    }//GEN-LAST:event_pnlCameraMouseEntered

    private void pnlCameraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCameraMouseExited
        pnlCamera.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlCameraMouseExited

    private void pnlGianTrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGianTrongMouseClicked
        this.OpenGianTrong();
    }//GEN-LAST:event_pnlGianTrongMouseClicked

    private void pnlGianTrongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGianTrongMouseEntered
        pnlGianTrong.setBackground(c);
    }//GEN-LAST:event_pnlGianTrongMouseEntered

    private void pnlGianTrongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGianTrongMouseExited
        pnlGianTrong.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlGianTrongMouseExited

    private void pnlGiaoViecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGiaoViecMouseClicked
        this.OpenGiaoViec();
        pnlGiaoViec.setBackground(c);
    }//GEN-LAST:event_pnlGiaoViecMouseClicked

    private void pnlGiaoViecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGiaoViecMouseEntered
        pnlGiaoViec.setBackground(c);
    }//GEN-LAST:event_pnlGiaoViecMouseEntered

    private void pnlGiaoViecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGiaoViecMouseExited
        pnlGiaoViec.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlGiaoViecMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        this.openDangXuat();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setForeground(new Color(0, 0, 255));
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setForeground(new Color(51, 153, 255));
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblsunrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsunrainMouseClicked
        new WeatherJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblsunrainMouseClicked

    private void lblweatherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblweatherMouseClicked
        new WeatherJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblweatherMouseClicked

    private void lblweatherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblweatherMouseEntered
        lblweather.setForeground(new Color(51, 153, 255));
    }//GEN-LAST:event_lblweatherMouseEntered

    private void lblweatherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblweatherMouseExited
        lblweather.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblweatherMouseExited

    private void pnlhienthiNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhienthiNVMouseClicked
        this.OpenNhanVien();
    }//GEN-LAST:event_pnlhienthiNVMouseClicked

    private void pnlhienthiNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhienthiNVMouseEntered
        pnlhienthiNV.setBackground(c);
    }//GEN-LAST:event_pnlhienthiNVMouseEntered

    private void pnlhienthiNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhienthiNVMouseExited
        pnlhienthiNV.setBackground(new Color(102, 255, 204));
    }//GEN-LAST:event_pnlhienthiNVMouseExited

    private void pnlThoiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoiTietMouseClicked
        new WeatherJDialog(this, true).setVisible(true);
        pnlThoiTiet.setBackground(c);
    }//GEN-LAST:event_pnlThoiTietMouseClicked

    private void pnlThoiTietMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoiTietMouseEntered
        pnlThoiTiet.setBackground(c);
    }//GEN-LAST:event_pnlThoiTietMouseEntered

    private void pnlThoiTietMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoiTietMouseExited
        pnlThoiTiet.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlThoiTietMouseExited

    private void ManhinhliveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManhinhliveMouseClicked
        this.pause();
    }//GEN-LAST:event_ManhinhliveMouseClicked

    private void pnlnhanviecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlnhanviecMouseClicked
        this.OpenTodo();
    }//GEN-LAST:event_pnlnhanviecMouseClicked

    private void pnlnhanviecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlnhanviecMouseEntered
        pnlnhanviec.setBackground(c);
    }//GEN-LAST:event_pnlnhanviecMouseEntered

    private void pnlnhanviecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlnhanviecMouseExited
        pnlnhanviec.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlnhanviecMouseExited

    private void pnlxacnhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlxacnhanMouseClicked
        this.Opendoing();
    }//GEN-LAST:event_pnlxacnhanMouseClicked

    private void pnlxacnhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlxacnhanMouseEntered
        pnlxacnhan.setBackground(c);
    }//GEN-LAST:event_pnlxacnhanMouseEntered

    private void pnlxacnhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlxacnhanMouseExited
        pnlxacnhan.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlxacnhanMouseExited

    private void pnlThoiTiet1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoiTiet1MouseClicked
        new WeatherJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_pnlThoiTiet1MouseClicked

    private void pnlThoiTiet1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoiTiet1MouseEntered
        pnlThoiTiet1.setBackground(c);
    }//GEN-LAST:event_pnlThoiTiet1MouseEntered

    private void pnlThoiTiet1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoiTiet1MouseExited
        pnlThoiTiet1.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlThoiTiet1MouseExited

    private void tblNhatKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhatKyMouseClicked
        this.OpenNhatky();
    }//GEN-LAST:event_tblNhatKyMouseClicked

    private void pnlBonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBonusMouseClicked
        MsgBox.alert(this, "Tổng công việc: " + nkdao.selectDoneByMonth(Auth.user.getMaNV()).size()
                + "\n--------------------"
                + "\nTrồng cây: " + nkdao.selectDoneMonthByTrangThaiAndCongViecAndNhanVien(3, "Trồng cây", Auth.user.getMaNV()).size()
                + "\nChăm sóc: " + nkdao.selectDoneMonthByTrangThaiAndCongViecAndNhanVien(3, "Chăm sóc", Auth.user.getMaNV()).size()
                + "\nThu hoạch: " + nkdao.selectDoneMonthByTrangThaiAndCongViecAndNhanVien(3, "Thu hoạch", Auth.user.getMaNV()).size()
                + "\n--------------------"
                + "\nHủy bỏ: " + nkdao.selectDoneMonthByTrangThaiAndNhanVien(2, Auth.user.getMaNV()).size()
                + "\n--------------------"
                + "\nHoa hồng: " + nkdao.selectDoneMonthByTrangThaiAndNhanVien(5, Auth.user.getMaNV()).size()
        );
    }//GEN-LAST:event_pnlBonusMouseClicked

    private void pnlBonusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBonusMouseEntered
        pnlBonus.setBackground(c);
    }//GEN-LAST:event_pnlBonusMouseEntered

    private void pnlBonusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBonusMouseExited
        pnlBonus.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_pnlBonusMouseExited

    private void pnlNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseClicked
        this.OpenNhanVien();
    }//GEN-LAST:event_pnlNhanVienMouseClicked

    private void pnlNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseEntered
        pnlNhanVien.setBackground(c);
    }//GEN-LAST:event_pnlNhanVienMouseEntered

    private void pnlNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseExited
        pnlNhanVien.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlNhanVienMouseExited

    private void pnlCayTrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCayTrongMouseClicked
        this.OpenCayTrong();
    }//GEN-LAST:event_pnlCayTrongMouseClicked

    private void pnlCayTrongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCayTrongMouseEntered
        pnlCayTrong.setBackground(c);
    }//GEN-LAST:event_pnlCayTrongMouseEntered

    private void pnlCayTrongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCayTrongMouseExited
        pnlCayTrong.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlCayTrongMouseExited

    private void pnlNhatKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhatKyMouseClicked
        this.OpenNhatky();
    }//GEN-LAST:event_pnlNhatKyMouseClicked

    private void pnlNhatKyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhatKyMouseEntered
        pnlNhatKy.setBackground(c);
    }//GEN-LAST:event_pnlNhatKyMouseEntered

    private void pnlNhatKyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhatKyMouseExited
        // TODO add your handling code here:
        pnlNhatKy.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnlNhatKyMouseExited

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        if (Auth.isManager()) {
            new ThongKeJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập vào chức năng này !");
        }

    }//GEN-LAST:event_btnThongkeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TongQuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        java.awt.EventQueue.invokeLater(() -> {
            new TongQuan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoDoing;
    private javax.swing.JLabel LogoKhohang;
    private javax.swing.JPanel Manhinhlive;
    private javax.swing.JTabbedPane TabsMnu;
    private javax.swing.JButton btnThongke;
    private com.farmsys.Helper.ImageAvatar imageAvatar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDemDangLam;
    private javax.swing.JLabel lblDemDoneByMonth;
    private javax.swing.JLabel lblDemKhoHang;
    private javax.swing.JLabel lblDemNhanViec;
    private javax.swing.JLabel lblDemSoCayTH;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblGiaoviec;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblNhanvien;
    private javax.swing.JLabel lblbonus;
    private javax.swing.JLabel lblcamera;
    private javax.swing.JLabel lblcaycanTH;
    private javax.swing.JLabel lblcaytrong1;
    private javax.swing.JLabel lblcaytrong2;
    private javax.swing.JLabel lblcaytrong3;
    private javax.swing.JLabel lblcongvieccanlam;
    private javax.swing.JLabel lbldashboard;
    private javax.swing.JLabel lbldemNV;
    private javax.swing.JLabel lblgiantrong;
    private javax.swing.JLabel lblhoten;
    private javax.swing.JLabel lblkhohang;
    private javax.swing.JLabel lblmenunhanviec;
    private javax.swing.JLabel lblnhanviec;
    private javax.swing.JLabel lblsunrain;
    private javax.swing.JLabel lblthoitiet;
    private javax.swing.JLabel lblthoitiet1;
    private javax.swing.JLabel lbltrangchu;
    private javax.swing.JLabel lblvaitro;
    private javax.swing.JLabel lblweather;
    private javax.swing.JLabel lblxnht;
    private javax.swing.JLabel logoDollar;
    private javax.swing.JLabel logoGiaoviec;
    private javax.swing.JLabel logoNhanVien;
    private javax.swing.JLabel logoNhanviec;
    private javax.swing.JLabel logoNhatKy;
    private javax.swing.JLabel logoThoitiet;
    private javax.swing.JLabel logoThoitiet1;
    private javax.swing.JLabel logocaycanTH;
    private javax.swing.JLabel logocaycanTH1;
    private javax.swing.JLabel logocaytrong2;
    private javax.swing.JLabel logodashboard;
    private javax.swing.JLabel logogiantrong;
    private javax.swing.JLabel logolive;
    private javax.swing.JLabel logomenunhanviec;
    private javax.swing.JLabel logotrangchu;
    private javax.swing.JLabel logoxnht;
    private javax.swing.JPanel penalTong;
    private javax.swing.JPanel pnlBonus;
    private javax.swing.JPanel pnlCamera;
    private javax.swing.JPanel pnlCayTrong;
    private javax.swing.JPanel pnlCaycanTH;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlGianTrong;
    private javax.swing.JPanel pnlGiaoViec;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlNhatKy;
    private javax.swing.JPanel pnlThoiTiet;
    private javax.swing.JPanel pnlThoiTiet1;
    private javax.swing.JPanel pnlTrangchu;
    private javax.swing.JPanel pnlavatar;
    private javax.swing.JPanel pnldoing;
    private javax.swing.JPanel pnlfoot;
    private javax.swing.JPanel pnlhead;
    private javax.swing.JPanel pnlhienthiNV;
    private javax.swing.JPanel pnlkhohang;
    private javax.swing.JPanel pnlmenu;
    private javax.swing.JPanel pnlnhanviec;
    private javax.swing.JPanel pnlnhanvien;
    private javax.swing.JPanel pnltodo;
    private javax.swing.JPanel pnltongquat;
    private javax.swing.JPanel pnltruongphong;
    private javax.swing.JPanel pnlxacnhan;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblNhatKy;
    // End of variables declaration//GEN-END:variables
    Color c = new Color(204, 255, 204);
    private JsonResult result;
    private int idx = 0;

    NhatKyDAO nkdao = new NhatKyDAO();
    NhanVienDAO nvdao = new NhanVienDAO();
    ThuHoachDAO thdao = new ThuHoachDAO();
    KhoHangDAO khdao = new KhoHangDAO();

    MP3Player Ping = new MP3Player(new File("src\\Sounds\\thongbao.mp3"));
    MP3Player Ping3 = new MP3Player(new File("src\\Sounds\\UI.mp3"));

    private TongQuan.DaemonThread myThread = null;
    int count = 0;
    VideoCapture webSource = null;
    Mat frame = new Mat();
    MatOfByte mem = new MatOfByte();
    CascadeClassifier faceDetector = new CascadeClassifier(TongQuan.class.getResource("haarcascade_frontalface_alt.xml").getPath().substring(1));
    MatOfRect faceDetections = new MatOfRect();

    private void init() {
        this.setIconImage(XImage.getAppIcon());
        result = HandleAPI.getJsonData((String) "Saigon");
        setThoiTiet();
        //this.setIconImage(XImage.getAppIcon());
        this.setLocationRelativeTo(null);

        new ChaoJdialog(this, true).setVisible(true);
        new Loadwelcome(this, true).setVisible(true);
        new Loadwelcome(this, true).setVisible(false);
        Ping3.play();
        new DangNhapJDialog(this, true).setVisible(true);
        Ping3.stop();
        new welcomeunscreen(this, true).setVisible(true);
        Ping.play();
        loadLbl();
        addpanel();
        new Timer(1000, (ActionEvent e) -> {
            Date now = new Date();
            SimpleDateFormat formater = new SimpleDateFormat("hh:mm a");
            String text = formater.format(now);
            lblDongHo.setText(text);
            this.count();
        }).start();
        this.fillTableNhatKyAll();

        if (Auth.isManager()) {
            TabsMnu.setSelectedIndex(0);
        } else {
            TabsMnu.setSelectedIndex(1);
        }
    }

    float getBonusMonth() {
        int tongTrongCay = nkdao.selectDoneMonthByTrangThaiAndCongViecAndNhanVien(3, "Trồng cây", Auth.user.getMaNV()).size();
        int tongChamSoc = nkdao.selectDoneMonthByTrangThaiAndCongViecAndNhanVien(3, "Chăm sóc", Auth.user.getMaNV()).size();
        int tongThuHoach = nkdao.selectDoneMonthByTrangThaiAndCongViecAndNhanVien(3, "Thu hoạch", Auth.user.getMaNV()).size();
        int tongCancel = nkdao.selectDoneMonthByTrangThaiAndNhanVien(2, Auth.user.getMaNV()).size();
        int tongHoaHong = nkdao.selectDoneMonthByTrangThaiAndNhanVien(5, Auth.user.getMaNV()).size();
        float bonusTrongCay, bonusChamSoc, bonusThuHoach, bonusCancel, bonusHoaHong, bonus;

        // sét KPI trồng cây và trả về tiền thưởng trồng cây
        if (tongTrongCay > 50) {
            bonusTrongCay = (float) (tongTrongCay * 1.5);
        } else if (tongTrongCay > 30) {
            bonusTrongCay = (float) (tongTrongCay * 1.25);
        } else {
            bonusTrongCay = tongTrongCay * 1;
        }

        // sét KPI chăm sóc và trả về tiền thưởng thu hoạch
        if (tongChamSoc > 150) {
            bonusChamSoc = (float) (tongChamSoc * 1.75);
        } else if (tongChamSoc > 100) {
            bonusChamSoc = (float) (tongChamSoc * 1.5);
        } else if (tongChamSoc > 50) {
            bonusChamSoc = (float) (tongChamSoc * 1.25);
        } else {
            bonusChamSoc = tongChamSoc * 1;
        }

        // sét KPI thu hoạch và trả về tiền thưởng thu hoạch
        if (tongThuHoach > 50) {
            bonusThuHoach = (float) (tongThuHoach * 1.5);
        } else if (tongThuHoach > 25) {
            bonusThuHoach = (float) (tongThuHoach * 1.25);
        } else {
            bonusThuHoach = (float) (tongThuHoach * 1);
        }

        //sét KPI cancel và trả về tiền phạt
        if (tongCancel > 10) {
            bonusCancel = tongCancel * -2;
        } else if (tongCancel > 5) {
            bonusCancel = (float) (tongCancel * -1.5);
        } else if (tongCancel > 3) {
            bonusCancel = (float) (tongCancel * -1.25);
        } else {
            bonusCancel = tongCancel * 0;
        }

        //tìm sản phẩm đã bán và trả về hoa hồng
        bonusHoaHong = tongHoaHong * 2;

        return bonus = bonusTrongCay + bonusChamSoc + bonusThuHoach + bonusCancel + bonusHoaHong;
    }

    void count() {
        lblDemNhanViec.setText(nkdao.selectByTrangThaivaTennv(0, Auth.user.getMaNV()).size() + "");
        lblDemDangLam.setText(nkdao.selectByTrangThaivaTennv(1, Auth.user.getMaNV()).size() + "");
        lblDemKhoHang.setText(khdao.selectAll().size() + "");
        lblDemDoneByMonth.setText(this.getBonusMonth() + "");

        lblDemSoCayTH.setText(thdao.selectAll().size() + "");
        lbldemNV.setText(nvdao.selectAll().size() + "");

    }

// line chart
    void setThoiTiet() {
        String weath = " Weather: " + result.getList()[idx].getWeather()[0].getDescription();
        lblweather.setText(weath);
        String text = lblweather.getText();
        if (text.contains("clouds")) {
            lblsunrain.setIcon(new ImageIcon("src\\com\\farmsys\\icons\\cloud_100px.png"));
        } else if (text.contains("rain")) {
            lblsunrain.setIcon(new ImageIcon("src\\com\\farmsys\\icons\\rain_100px.png"));
        }
    }

    private void loadLbl() {
        lblhoten.setText(DangNhapJDialog.HienThihoten());
        lblvaitro.setText(DangNhapJDialog.HienThivaitro());
        edit();
    }

    private void openDangXuat() {
        int ask = JOptionPane.showConfirmDialog(this, "Bạn có chắc là mình muốn đăng xuất ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (ask == 0) {
            this.dispose();
            new TongQuan().setVisible(true);
        }
    }

    private void OpenNhanVien() {
        if (Auth.isManager()) {

            tabs.setSelectedIndex(6);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void OpenGianTrong() {
        if (Auth.isManager()) {

            tabs.setSelectedIndex(8);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void OpenCayTrong() {
        if (Auth.isManager()) {

            tabs.setSelectedIndex(4);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void OpenNhatky() {
        if (Auth.isLogin()) {

            tabs.setSelectedIndex(2);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    private void OpenGiaoViec() {
        if (Auth.isManager()) {

            tabs.setSelectedIndex(5);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void OpenTodo() {
        if (Auth.isLogin()) {

            tabs.setSelectedIndex(3);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    private void Opendoing() {
        if (Auth.isLogin()) {

            tabs.setSelectedIndex(7);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    private void Openchart() {
        if (Auth.isLogin()) {

            tabs.setSelectedIndex(9);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    private void OpenLive() {
        if (Auth.isLogin()) {
            this.start();
            tabs.setSelectedIndex(1);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    private void OpenKhohang() {
        if (Auth.isManager()) {

            tabs.setSelectedIndex(10);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    void addpanel() {
        NhatKyJPanel nkpnJPanel = new NhatKyJPanel();
        NhanViecJPanel nhanviecJPanel = new NhanViecJPanel();
        CayTrongPanel cayTrongPanel = new CayTrongPanel();
        GiaoViecJPanel giaoViecJPanel = new GiaoViecJPanel();
        NhanVienPanel nhanVienPanel = new NhanVienPanel();
        HoanThanhcvJPanel hoanThanhcvJPanel = new HoanThanhcvJPanel();
        GianTrongJPanel gianTrongJPanel = new GianTrongJPanel();
        ChartJPanel chartPanel = new ChartJPanel();
        KhoHangJPanel khoHangJPanel = new KhoHangJPanel();

        tabs.addTab("0", nkpnJPanel);
        tabs.addTab("1", nhanviecJPanel);
        tabs.addTab("2", cayTrongPanel);
        tabs.addTab("3", giaoViecJPanel);
        tabs.addTab("4", nhanVienPanel);
        tabs.addTab("5", hoanThanhcvJPanel);
        tabs.addTab("6", gianTrongJPanel);
        tabs.addTab("7", chartPanel);
        tabs.addTab("8", khoHangJPanel);

    }

    private void fillTableNhatKyAll() {
        DefaultTableModel model = (DefaultTableModel) tblNhatKy.getModel();
        model.setRowCount(0);
        List<NhatKy> list = nkdao.selectAllMonth();
        list.forEach(nk -> {
            model.addRow(new Object[]{
                nk.getTenCV(),
                nk.getTenCay(),
                nk.getTenGian(),
                nk.getChiTiet(),
                nk.getNguoiTao(),
                nk.getNhanVien(),
                nk.getNgayBatDau(),
                nk.getNgayKetThuc(),
                nk.toString()
            });
        });
    }

    void setAvatar(NhanVien nv) {
        if (nv.getHinh() != null) {
            imageAvatar.setToolTipText(nv.getHinh());
            ImageIcon icon = XImage.read(nv.getHinh()); // Lấy địa chỉ của file Icon
            //Chuyển Icon sang image và điều chỉnh kích thước
            Image scaleIcon = icon.getImage().getScaledInstance(imageAvatar.getWidth(), imageAvatar.getHeight(), Image.SCALE_DEFAULT);
            imageAvatar.setImage(new javax.swing.ImageIcon(scaleIcon));
        }
    }

    void edit() {
        String name = lblhoten.getText();
        NhanVien nv = nvdao.selectHinh(name);
        this.setAvatar(nv);
    }

    class DaemonThread implements Runnable {

        protected volatile boolean runnable = false;

        @Override
        public void run() {
            synchronized (this) {
                while (runnable) {
                    if (webSource.grab()) {
                        try {
                            webSource.retrieve(frame);
                            Graphics g = Manhinhlive.getGraphics();
                            faceDetector.detectMultiScale(frame, faceDetections);
                            for (Rect rect : faceDetections.toArray()) {
                                // System.out.println("ttt");
                                Core.rectangle(frame, new Point(rect.x, rect.y), new Point(rect.x + rect.width, rect.y + rect.height),
                                        new Scalar(0, 255, 0));
                            }
                            Highgui.imencode(".bmp", frame, mem);
                            Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));
                            BufferedImage buff = (BufferedImage) im;
                            if (g.drawImage(buff, 0, 0, getWidth(), getHeight(), 0, 0, buff.getWidth(), buff.getHeight(), null)) {
                                if (runnable == false) {
                                    System.out.println("Paused ..... ");
                                    this.wait();
                                }
                            }
                        } catch (IOException | InterruptedException ex) {
                            System.out.println("Error!!");
                        }
                    }
                }
            }
        }
    }

    public void start() {
        webSource = new VideoCapture(0); // video capture from default cam
        myThread = new DaemonThread(); //create object of threat class
        Thread t = new Thread(myThread);
        t.setDaemon(true);
        myThread.runnable = true;
        t.start();

    }

    public void pause() {
        myThread.runnable = false;
        webSource.release();

    }

}
